---
title: "Capstone Project"
author: "Chisimdiri"
date: "12/23/2021"
output:
  word_document: default
  pdf_document: default
---

## Cyclist BikeShare Analysis

```{r Load packages}
library('tidyverse')
library('lubridate')
library('ggplot2')
```

```{r Set Working Directory}
setwd("C:/Users/Chisim/Desktop/Divvy_Trips_2019_Q1")
getwd()
```

```{r Load data to R Studio}
q1_2019 <- read.csv('Divvy_Trips_2019_Q1.csv')
q2_2019 <- read.csv('Divvy_Trips_2019_Q2.csv')
q3_2019 <- read.csv('Divvy_Trips_2019_Q3.csv')
q4_2019 <- read.csv('Divvy_Trips_2019_Q4.csv')
```

```{r View data set columns}
colnames(q1_2019)
colnames(q2_2019)
colnames(q3_2019)
colnames(q4_2019)
```
```{r Rename Column names to the new style format for the year 2020}
q1_2019 <- rename(q1_2019, ride_id=trip_id,
                  rideable_type=bikeid,
                  started_at=start_time,
                  ended_at=end_time,
                  start_station_name=from_station_name,
                  end_station_name=to_station_name,
                  member_casual=usertype
                  ) 
q1_2019 <- rename(q1_2019, start_station_id=from_station_id,
                  end_station_id=to_station_id)

q2_2019 <- rename(q2_2019, ride_id=X01...Rental.Details.Rental.ID,
                  rideable_type=X01...Rental.Details.Bike.ID,
                  started_at=X01...Rental.Details.Local.Start.Time,
                  ended_at=X01...Rental.Details.Local.End.Time,
                  start_station_name=X03...Rental.Start.Station.Name,
                  end_station_name=X02...Rental.End.Station.Name,
                  member_casual=User.Type,
                  tripduration=X01...Rental.Details.Duration.In.Seconds.Uncapped,
                  start_station_id=X03...Rental.Start.Station.ID,
                  end_station_id=X02...Rental.End.Station.ID,
                  gender=Member.Gender,
                  birthyear=X05...Member.Details.Member.Birthday.Year)

q3_2019 <- rename(q3_2019, ride_id=trip_id,
                  rideable_type=bikeid,
                  started_at=start_time,
                  ended_at=end_time,
                  start_station_name=from_station_name,
                  end_station_name=to_station_name,
                  member_casual=usertype,
                  start_station_id=from_station_id,
                  end_station_id=to_station_id)
q4_2019 <- rename(q4_2019, ride_id=trip_id,
                  rideable_type=bikeid,
                  started_at=start_time,
                  ended_at=end_time,
                  start_station_name=from_station_name,
                  end_station_name=to_station_name,
                  member_casual=usertype,
                  start_station_id=from_station_id,
                  end_station_id=to_station_id)
```

```{r Check structure of data set}
str(q1_2019)
str(q2_2019)
str(q3_2019)
str(q4_2019)

```

```{r Convert ride_id into character so it can stack properly in the table}
q1_2019 <- mutate(q1_2019, ride_id=as.character(ride_id))
q2_2019 <- mutate(q2_2019, ride_id=as.character(ride_id))
q3_2019 <- mutate(q3_2019, ride_id=as.character(ride_id))
q4_2019 <- mutate(q4_2019, ride_id=as.character(ride_id))
```

```{r Join columns in all 4 data sets into 1}
bike_trips_2019 <- bind_rows(q2_2019,q3_2019,q4_2019,q1_2019)
```

```{r Data cleaning}
colnames(bike_trips_2019)
nrow(bike_trips_2019)
dim(bike_trips_2019)
head(bike_trips_2019, 5)
str(bike_trips_2019)
```
```{r Standardize member_casual column to contain a consistent output}
bike_trips_2019 <- bike_trips_2019 %>% 
    mutate(member_casual = recode(member_casual
                           ,"Subscriber" = "member"
                           ,"Customer" = "casual"))

```

```{r Make separate columns for dates}
bike_trips_2019 %>% 
  add_column(date = 'NA')
bike_trips_2019$date <- as.Date(bike_trips_2019$started_at)
bike_trips_2019 %>% 
  add_column(month = 'NA')
bike_trips_2019$month <- format(as.Date(bike_trips_2019$date), '%b')
bike_trips_2019 %>% 
  add_column(day = 'NA')
bike_trips_2019$day <- format(as.Date(bike_trips_2019$date), '%d')
bike_trips_2019 %>%
  add_column(year = 'NA')
bike_trips_2019$year <- format(as.Date(bike_trips_2019$date), '%y')
bike_trips_2019 %>%
  add_column(day_of_the_week = 'NA')
bike_trips_2019$day_of_the_week <- format(as.Date(bike_trips_2019$date), '%A')
```


```{r Filtering Null values and Bike maintenance trips}
bike_trips_2019$tripduration <- as.numeric(as.character(bike_trips_2019$tripduration))
str(bike_trips_2019)
bike_trips_2019_v2 <- bike_trips_2019[!(bike_trips_2019$start_station_name == 'HQ QR' | bike_trips_2019$tripduration == 'NA'),]
bike_trips_2019_v2 <- bike_trips_2019_v2 %>%
  filter(tripduration != 'NA')
bike_trips_2019_v2$tripduration <- as.numeric(as.character(bike_trips_2019_v2$tripduration))
```

```{r Aggregate data to discover trends}
aggregate(bike_trips_2019_v2$tripduration~bike_trips_2019_v2$member_casual, FUN = mean)
aggregate(bike_trips_2019_v2$tripduration~bike_trips_2019_v2$member_casual, FUN = median)
aggregate(bike_trips_2019_v2$tripduration~bike_trips_2019_v2$member_casual, FUN = max)
aggregate(bike_trips_2019_v2$tripduration~bike_trips_2019_v2$member_casual, FUN = min)
aggregate(bike_trips_2019_v2$tripduration~bike_trips_2019_v2$start_station_name, FUN = mean)
aggregate(bike_trips_2019_v2$tripduration~bike_trips_2019_v2$end_station_name + bike_trips_2019_v2$day_of_the_week, FUN = mean)
bike_trips_2019_v4 <- aggregate(bike_trips_2019_v2$tripduration~bike_trips_2019_v2$start_station_name + bike_trips_2019_v2$day_of_the_week + bike_trips_2019_v2$member_casual, FUN = mean)
```

```{r Get the Number of rides and average duration for each denomination of riders}
aggregate(bike_trips_2019_v2$tripduration~bike_trips_2019_v2$member_casual + bike_trips_2019_v2$day_of_the_week, FUN = mean)
bike_trips_2019_v2 %>% 
  group_by(member_casual, month) %>%
  summarise(number_of_rides = n(),
            average_duration = mean(tripduration))
```

```{r Chart for Days vs. Ride Numbers and Months vs Average of Ride Numbers}

bike_trips_2019_v3 <-
bike_trips_2019_v2 %>% 
  group_by(member_casual, day_of_the_week) %>%
  summarise(number_of_rides = n(),
            average_duration = mean(tripduration))
bike_trips_2019_v3 <- bike_trips_2019_v3 [-15,]
bike_trips_2019_v3 %>%
  ggplot(aes(x = day_of_the_week, y = number_of_rides, fill = member_casual)) + geom_col(position = 'dodge') + coord_flip() + labs(title = 'Days vs. Rider Numbers')
```
```{r}
bike_trips_2019_v4 <- bike_trips_2019_v2 %>% 
  group_by(member_casual, month) %>%
  summarise(number_of_rides = n(),
            average_duration = mean(tripduration))
bike_trips_2019_v4 %>%
  ggplot(aes(x = month, y = number_of_rides, fill = member_casual)) + geom_col(position = 'dodge') + coord_flip() + labs(title = 'Months vs. Rider Numbers')
```


```{r Chart for Days vs. Average Ride Duration}
bike_trips_2019_v3 %>%
  ggplot(aes(x = day_of_the_week, y = average_duration, fill = member_casual)) + geom_col(position = 'dodge') + coord_flip() + labs(title = 'Days vs. Average Ride Duration (seconds)')
```


```{r Chart for Months vs. Average Ride Duration}
bike_trips_2019_v4 %>%
  ggplot(aes(x = month, y = average_duration, fill = member_casual)) + geom_col(position = 'dodge') + coord_flip() + labs(title = 'Months vs. Average Ride Duration (seconds)')

```


```{r}
## Conclusions
#I noticed Saturday and Sunday are the days with the highest number of rides for the casual group and also within the group of casual riders those days have the highest ride duration, most likely because they use the bikes for things like exercise and leisure activities. Also another thing I noticed in this data set is that in the months synonymous to the summer period the number of casual riders increase as well as the average ride duration of casual riders. I would suggest making discounted prices during the summer period for incoming members to compel the casual group into subscribing to a membership plan and also creating exercise themed ads to encourage casual riders to become members.
```
